[package]
name = "cvm_cli"
authors = ["Lucas Arch <luketsx@icloud.com>"]
categories = ["development-tools", "command-line-utilities"]
description = "A powerful command-line tool for managing semantic versioning of Rust crates. Easily bump versions (major, minor, patch), update Cargo.toml files, and streamline your release workflow with automated version management."
edition = "2021"
keywords = ["rust", "cargo", "versioning", "semver", "cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucasaarch/cvm"
version = "1.0.8"

[[bin]]
name = "cvm"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.101"
inquire = "0.9.3"
semver = "1.0.27"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.12"

[dependencies.clap]
features = ["derive"]
version = "4.5.57"
